grails-app/domain/webservicetest_two_three_eleven/Boat.groovy
package webservicetest_two_three_eleven
import grails.rest.Resource

@Resource(uri='/books', formats=['json','xml'])
class Boat {
    Integer boatID
    String boatName
    String marina
    String make
    String model
    String length
    Integer year
    String engine
    String propulsion
    String fuelCapacity
    String fuelType
    String category
    String activities
    Integer referralID
    static constraints = {

    }
}

grails-app/domain/webservicetest_two_three_eleven/Book.groovy
package webservicetest_two_three_eleven
import grails.rest.Resource

@Resource(uri='/books', formats=['json','xml'])
class Book {
    String title
    String author
    static constraints = {
    }
}

grails-app/controllers/webservicetest_two_three_eleven/BoatController.groovy
package webservicetest_two_three_eleven



import static org.springframework.http.HttpStatus.*
import grails.transaction.Transactional

@Transactional(readOnly = true)
class BoatController {

    static allowedMethods = [save: "POST", update: "PUT", delete: "DELETE"]

    def index(Integer max) {
        params.max = Math.min(max ?: 10, 100)
        respond Boat.list(params), model: [boatInstanceCount: Boat.count()]
    }

    def show(Boat boatInstance) {
        respond boatInstance
    }

    def create() {
        respond new Boat(params)
    }

    @Transactional
    def save(Boat boatInstance) {
        if (boatInstance == null) {
            notFound()
            return
        }

        if (boatInstance.hasErrors()) {
            respond boatInstance.errors, view: 'create'
            return
        }

        boatInstance.save flush: true

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.created.message', args: [message(code: 'boat.label', default: 'Boat'), boatInstance.id])
                redirect boatInstance
            }
            '*' { respond boatInstance, [status: CREATED] }
        }
    }

    def edit(Boat boatInstance) {
        respond boatInstance
    }

    @Transactional
    def update(Boat boatInstance) {
        if (boatInstance == null) {
            notFound()
            return
        }

        if (boatInstance.hasErrors()) {
            respond boatInstance.errors, view: 'edit'
            return
        }

        boatInstance.save flush: true

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.updated.message', args: [message(code: 'Boat.label', default: 'Boat'), boatInstance.id])
                redirect boatInstance
            }
            '*' { respond boatInstance, [status: OK] }
        }
    }

    @Transactional
    def delete(Boat boatInstance) {

        if (boatInstance == null) {
            notFound()
            return
        }

        boatInstance.delete flush: true

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.deleted.message', args: [message(code: 'Boat.label', default: 'Boat'), boatInstance.id])
                redirect action: "index", method: "GET"
            }
            '*' { render status: NO_CONTENT }
        }
    }

    protected void notFound() {
        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.not.found.message', args: [message(code: 'boat.label', default: 'Boat'), params.id])
                redirect action: "index", method: "GET"
            }
            '*' { render status: NOT_FOUND }
        }
    }
}

grails-app/controllers/webservicetest_two_three_eleven/BookController.groovy
package webservicetest_two_three_eleven



import static org.springframework.http.HttpStatus.*
import grails.transaction.Transactional

@Transactional(readOnly = true)
class BookController {

    static allowedMethods = [save: "POST", update: "PUT", delete: "DELETE"]

    def index(Integer max) {
        params.max = Math.min(max ?: 10, 100)
        respond Book.list(params), model:[bookInstanceCount: Book.count()]
    }

    def show(Book bookInstance) {
        respond bookInstance
    }

    def create() {
        respond new Book(params)
    }

    @Transactional
    def save(Book bookInstance) {
        if (bookInstance == null) {
            notFound()
            return
        }

        if (bookInstance.hasErrors()) {
            respond bookInstance.errors, view:'create'
            return
        }

        bookInstance.save flush:true

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.created.message', args: [message(code: 'book.label', default: 'Book'), bookInstance.id])
                redirect bookInstance
            }
            '*' { respond bookInstance, [status: CREATED] }
        }
    }

    def edit(Book bookInstance) {
        respond bookInstance
    }

    @Transactional
    def update(Book bookInstance) {
        if (bookInstance == null) {
            notFound()
            return
        }

        if (bookInstance.hasErrors()) {
            respond bookInstance.errors, view:'edit'
            return
        }

        bookInstance.save flush:true

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.updated.message', args: [message(code: 'Book.label', default: 'Book'), bookInstance.id])
                redirect bookInstance
            }
            '*'{ respond bookInstance, [status: OK] }
        }
    }

    @Transactional
    def delete(Book bookInstance) {

        if (bookInstance == null) {
            notFound()
            return
        }

        bookInstance.delete flush:true

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.deleted.message', args: [message(code: 'Book.label', default: 'Book'), bookInstance.id])
                redirect action:"index", method:"GET"
            }
            '*'{ render status: NO_CONTENT }
        }
    }

    protected void notFound() {
        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.not.found.message', args: [message(code: 'book.label', default: 'Book'), params.id])
                redirect action: "index", method: "GET"
            }
            '*'{ render status: NOT_FOUND }
        }
    }
}

grails-app/views/boat/_form.gsp
<%@ page import="webservicetest_two_three_eleven.Boat" %>



<div class="fieldcontain ${hasErrors(bean: boatInstance, field: 'activities', 'error')} required">
	<label for="activities">
		<g:message code="boat.activities.label" default="Activities" />
		<span class="required-indicator">*</span>
	</label>
	<g:textField name="activities" required="" value="${boatInstance?.activities}"/>

</div>

<div class="fieldcontain ${hasErrors(bean: boatInstance, field: 'boatID', 'error')} required">
	<label for="boatID">
		<g:message code="boat.boatID.label" default="Boat ID" />
		<span class="required-indicator">*</span>
	</label>
	<g:field name="boatID" type="number" value="${boatInstance.boatID}" required=""/>

</div>

<div class="fieldcontain ${hasErrors(bean: boatInstance, field: 'boatName', 'error')} required">
	<label for="boatName">
		<g:message code="boat.boatName.label" default="Boat Name" />
		<span class="required-indicator">*</span>
	</label>
	<g:textField name="boatName" required="" value="${boatInstance?.boatName}"/>

</div>

<div class="fieldcontain ${hasErrors(bean: boatInstance, field: 'category', 'error')} required">
	<label for="category">
		<g:message code="boat.category.label" default="Category" />
		<span class="required-indicator">*</span>
	</label>
	<g:textField name="category" required="" value="${boatInstance?.category}"/>

</div>

<div class="fieldcontain ${hasErrors(bean: boatInstance, field: 'engine', 'error')} required">
	<label for="engine">
		<g:message code="boat.engine.label" default="Engine" />
		<span class="required-indicator">*</span>
	</label>
	<g:textField name="engine" required="" value="${boatInstance?.engine}"/>

</div>

<div class="fieldcontain ${hasErrors(bean: boatInstance, field: 'fuelCapacity', 'error')} required">
	<label for="fuelCapacity">
		<g:message code="boat.fuelCapacity.label" default="Fuel Capacity" />
		<span class="required-indicator">*</span>
	</label>
	<g:textField name="fuelCapacity" required="" value="${boatInstance?.fuelCapacity}"/>

</div>

<div class="fieldcontain ${hasErrors(bean: boatInstance, field: 'fuelType', 'error')} required">
	<label for="fuelType">
		<g:message code="boat.fuelType.label" default="Fuel Type" />
		<span class="required-indicator">*</span>
	</label>
	<g:textField name="fuelType" required="" value="${boatInstance?.fuelType}"/>

</div>

<div class="fieldcontain ${hasErrors(bean: boatInstance, field: 'length', 'error')} required">
	<label for="length">
		<g:message code="boat.length.label" default="Length" />
		<span class="required-indicator">*</span>
	</label>
	<g:textField name="length" required="" value="${boatInstance?.length}"/>

</div>

<div class="fieldcontain ${hasErrors(bean: boatInstance, field: 'make', 'error')} required">
	<label for="make">
		<g:message code="boat.make.label" default="Make" />
		<span class="required-indicator">*</span>
	</label>
	<g:textField name="make" required="" value="${boatInstance?.make}"/>

</div>

<div class="fieldcontain ${hasErrors(bean: boatInstance, field: 'marina', 'error')} required">
	<label for="marina">
		<g:message code="boat.marina.label" default="Marina" />
		<span class="required-indicator">*</span>
	</label>
	<g:textField name="marina" required="" value="${boatInstance?.marina}"/>

</div>

<div class="fieldcontain ${hasErrors(bean: boatInstance, field: 'model', 'error')} required">
	<label for="model">
		<g:message code="boat.model.label" default="Model" />
		<span class="required-indicator">*</span>
	</label>
	<g:textField name="model" required="" value="${boatInstance?.model}"/>

</div>

<div class="fieldcontain ${hasErrors(bean: boatInstance, field: 'propulsion', 'error')} required">
	<label for="propulsion">
		<g:message code="boat.propulsion.label" default="Propulsion" />
		<span class="required-indicator">*</span>
	</label>
	<g:textField name="propulsion" required="" value="${boatInstance?.propulsion}"/>

</div>

<div class="fieldcontain ${hasErrors(bean: boatInstance, field: 'referralID', 'error')} required">
	<label for="referralID">
		<g:message code="boat.referralID.label" default="Referral ID" />
		<span class="required-indicator">*</span>
	</label>
	<g:field name="referralID" type="number" value="${boatInstance.referralID}" required=""/>

</div>

<div class="fieldcontain ${hasErrors(bean: boatInstance, field: 'year', 'error')} required">
	<label for="year">
		<g:message code="boat.year.label" default="Year" />
		<span class="required-indicator">*</span>
	</label>
	<g:field name="year" type="number" value="${boatInstance.year}" required=""/>

</div>

grails-app/views/boat/create.gsp
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'boat.label', default: 'Boat')}" />
		<title><g:message code="default.create.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#create-boat" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="create-boat" class="content scaffold-create" role="main">
			<h1><g:message code="default.create.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
			<div class="message" role="status">${flash.message}</div>
			</g:if>
			<g:hasErrors bean="${boatInstance}">
			<ul class="errors" role="alert">
				<g:eachError bean="${boatInstance}" var="error">
				<li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
				</g:eachError>
			</ul>
			</g:hasErrors>
			<g:form url="[resource:boatInstance, action:'save']" >
				<fieldset class="form">
					<g:render template="form"/>
				</fieldset>
				<fieldset class="buttons">
					<g:submitButton name="create" class="save" value="${message(code: 'default.button.create.label', default: 'Create')}" />
				</fieldset>
			</g:form>
		</div>
	</body>
</html>

grails-app/views/boat/edit.gsp
<%@ page import="webservicetest_two_three_eleven.Boat" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'boat.label', default: 'Boat')}" />
		<title><g:message code="default.edit.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#edit-boat" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
				<li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="edit-boat" class="content scaffold-edit" role="main">
			<h1><g:message code="default.edit.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
			<div class="message" role="status">${flash.message}</div>
			</g:if>
			<g:hasErrors bean="${boatInstance}">
			<ul class="errors" role="alert">
				<g:eachError bean="${boatInstance}" var="error">
				<li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
				</g:eachError>
			</ul>
			</g:hasErrors>
			<g:form url="[resource:boatInstance, action:'update']" method="PUT" >
				<g:hiddenField name="version" value="${boatInstance?.version}" />
				<fieldset class="form">
					<g:render template="form"/>
				</fieldset>
				<fieldset class="buttons">
					<g:actionSubmit class="save" action="update" value="${message(code: 'default.button.update.label', default: 'Update')}" />
				</fieldset>
			</g:form>
		</div>
	</body>
</html>

grails-app/views/boat/index.gsp
<%@ page import="webservicetest_two_three_eleven.Boat" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'boat.label', default: 'Boat')}" />
		<title><g:message code="default.list.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#list-boat" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="list-boat" class="content scaffold-list" role="main">
			<h1><g:message code="default.list.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
				<div class="message" role="status">${flash.message}</div>
			</g:if>
			<table>
			<thead>
					<tr>
					
						<g:sortableColumn property="activities" title="${message(code: 'boat.activities.label', default: 'Activities')}" />
					
						<g:sortableColumn property="boatID" title="${message(code: 'boat.boatID.label', default: 'Boat ID')}" />
					
						<g:sortableColumn property="boatName" title="${message(code: 'boat.boatName.label', default: 'Boat Name')}" />
					
						<g:sortableColumn property="category" title="${message(code: 'boat.category.label', default: 'Category')}" />
					
						<g:sortableColumn property="engine" title="${message(code: 'boat.engine.label', default: 'Engine')}" />
					
						<g:sortableColumn property="fuelCapacity" title="${message(code: 'boat.fuelCapacity.label', default: 'Fuel Capacity')}" />
					
					</tr>
				</thead>
				<tbody>
				<g:each in="${boatInstanceList}" status="i" var="boatInstance">
					<tr class="${(i % 2) == 0 ? 'even' : 'odd'}">
					
						<td><g:link action="show" id="${boatInstance.id}">${fieldValue(bean: boatInstance, field: "activities")}</g:link></td>
					
						<td>${fieldValue(bean: boatInstance, field: "boatID")}</td>
					
						<td>${fieldValue(bean: boatInstance, field: "boatName")}</td>
					
						<td>${fieldValue(bean: boatInstance, field: "category")}</td>
					
						<td>${fieldValue(bean: boatInstance, field: "engine")}</td>
					
						<td>${fieldValue(bean: boatInstance, field: "fuelCapacity")}</td>
					
					</tr>
				</g:each>
				</tbody>
			</table>
			<div class="pagination">
				<g:paginate total="${boatInstanceCount ?: 0}" />
			</div>
		</div>
	</body>
</html>

grails-app/views/boat/show.gsp
<%@ page import="webservicetest_two_three_eleven.Boat" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'boat.label', default: 'Boat')}" />
		<title><g:message code="default.show.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#show-boat" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
				<li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="show-boat" class="content scaffold-show" role="main">
			<h1><g:message code="default.show.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
			<div class="message" role="status">${flash.message}</div>
			</g:if>
			<ol class="property-list boat">
			
				<g:if test="${boatInstance?.activities}">
				<li class="fieldcontain">
					<span id="activities-label" class="property-label"><g:message code="boat.activities.label" default="Activities" /></span>
					
						<span class="property-value" aria-labelledby="activities-label"><g:fieldValue bean="${boatInstance}" field="activities"/></span>
					
				</li>
				</g:if>
			
				<g:if test="${boatInstance?.boatID}">
				<li class="fieldcontain">
					<span id="boatID-label" class="property-label"><g:message code="boat.boatID.label" default="Boat ID" /></span>
					
						<span class="property-value" aria-labelledby="boatID-label"><g:fieldValue bean="${boatInstance}" field="boatID"/></span>
					
				</li>
				</g:if>
			
				<g:if test="${boatInstance?.boatName}">
				<li class="fieldcontain">
					<span id="boatName-label" class="property-label"><g:message code="boat.boatName.label" default="Boat Name" /></span>
					
						<span class="property-value" aria-labelledby="boatName-label"><g:fieldValue bean="${boatInstance}" field="boatName"/></span>
					
				</li>
				</g:if>
			
				<g:if test="${boatInstance?.category}">
				<li class="fieldcontain">
					<span id="category-label" class="property-label"><g:message code="boat.category.label" default="Category" /></span>
					
						<span class="property-value" aria-labelledby="category-label"><g:fieldValue bean="${boatInstance}" field="category"/></span>
					
				</li>
				</g:if>
			
				<g:if test="${boatInstance?.engine}">
				<li class="fieldcontain">
					<span id="engine-label" class="property-label"><g:message code="boat.engine.label" default="Engine" /></span>
					
						<span class="property-value" aria-labelledby="engine-label"><g:fieldValue bean="${boatInstance}" field="engine"/></span>
					
				</li>
				</g:if>
			
				<g:if test="${boatInstance?.fuelCapacity}">
				<li class="fieldcontain">
					<span id="fuelCapacity-label" class="property-label"><g:message code="boat.fuelCapacity.label" default="Fuel Capacity" /></span>
					
						<span class="property-value" aria-labelledby="fuelCapacity-label"><g:fieldValue bean="${boatInstance}" field="fuelCapacity"/></span>
					
				</li>
				</g:if>
			
				<g:if test="${boatInstance?.fuelType}">
				<li class="fieldcontain">
					<span id="fuelType-label" class="property-label"><g:message code="boat.fuelType.label" default="Fuel Type" /></span>
					
						<span class="property-value" aria-labelledby="fuelType-label"><g:fieldValue bean="${boatInstance}" field="fuelType"/></span>
					
				</li>
				</g:if>
			
				<g:if test="${boatInstance?.length}">
				<li class="fieldcontain">
					<span id="length-label" class="property-label"><g:message code="boat.length.label" default="Length" /></span>
					
						<span class="property-value" aria-labelledby="length-label"><g:fieldValue bean="${boatInstance}" field="length"/></span>
					
				</li>
				</g:if>
			
				<g:if test="${boatInstance?.make}">
				<li class="fieldcontain">
					<span id="make-label" class="property-label"><g:message code="boat.make.label" default="Make" /></span>
					
						<span class="property-value" aria-labelledby="make-label"><g:fieldValue bean="${boatInstance}" field="make"/></span>
					
				</li>
				</g:if>
			
				<g:if test="${boatInstance?.marina}">
				<li class="fieldcontain">
					<span id="marina-label" class="property-label"><g:message code="boat.marina.label" default="Marina" /></span>
					
						<span class="property-value" aria-labelledby="marina-label"><g:fieldValue bean="${boatInstance}" field="marina"/></span>
					
				</li>
				</g:if>
			
				<g:if test="${boatInstance?.model}">
				<li class="fieldcontain">
					<span id="model-label" class="property-label"><g:message code="boat.model.label" default="Model" /></span>
					
						<span class="property-value" aria-labelledby="model-label"><g:fieldValue bean="${boatInstance}" field="model"/></span>
					
				</li>
				</g:if>
			
				<g:if test="${boatInstance?.propulsion}">
				<li class="fieldcontain">
					<span id="propulsion-label" class="property-label"><g:message code="boat.propulsion.label" default="Propulsion" /></span>
					
						<span class="property-value" aria-labelledby="propulsion-label"><g:fieldValue bean="${boatInstance}" field="propulsion"/></span>
					
				</li>
				</g:if>
			
				<g:if test="${boatInstance?.referralID}">
				<li class="fieldcontain">
					<span id="referralID-label" class="property-label"><g:message code="boat.referralID.label" default="Referral ID" /></span>
					
						<span class="property-value" aria-labelledby="referralID-label"><g:fieldValue bean="${boatInstance}" field="referralID"/></span>
					
				</li>
				</g:if>
			
				<g:if test="${boatInstance?.year}">
				<li class="fieldcontain">
					<span id="year-label" class="property-label"><g:message code="boat.year.label" default="Year" /></span>
					
						<span class="property-value" aria-labelledby="year-label"><g:fieldValue bean="${boatInstance}" field="year"/></span>
					
				</li>
				</g:if>
			
			</ol>
			<g:form url="[resource:boatInstance, action:'delete']" method="DELETE">
				<fieldset class="buttons">
					<g:link class="edit" action="edit" resource="${boatInstance}"><g:message code="default.button.edit.label" default="Edit" /></g:link>
					<g:actionSubmit class="delete" action="delete" value="${message(code: 'default.button.delete.label', default: 'Delete')}" onclick="return confirm('${message(code: 'default.button.delete.confirm.message', default: 'Are you sure?')}');" />
				</fieldset>
			</g:form>
		</div>
	</body>
</html>

grails-app/views/book/_form.gsp
<%@ page import="webservicetest_two_three_eleven.Book" %>



<div class="fieldcontain ${hasErrors(bean: bookInstance, field: 'author', 'error')} required">
	<label for="author">
		<g:message code="book.author.label" default="Author" />
		<span class="required-indicator">*</span>
	</label>
	<g:textField name="author" required="" value="${bookInstance?.author}"/>

</div>

<div class="fieldcontain ${hasErrors(bean: bookInstance, field: 'title', 'error')} required">
	<label for="title">
		<g:message code="book.title.label" default="Title" />
		<span class="required-indicator">*</span>
	</label>
	<g:textField name="title" required="" value="${bookInstance?.title}"/>

</div>

grails-app/views/book/create.gsp
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'book.label', default: 'Book')}" />
		<title><g:message code="default.create.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#create-book" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="create-book" class="content scaffold-create" role="main">
			<h1><g:message code="default.create.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
			<div class="message" role="status">${flash.message}</div>
			</g:if>
			<g:hasErrors bean="${bookInstance}">
			<ul class="errors" role="alert">
				<g:eachError bean="${bookInstance}" var="error">
				<li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
				</g:eachError>
			</ul>
			</g:hasErrors>
			<g:form url="[resource:bookInstance, action:'save']" >
				<fieldset class="form">
					<g:render template="form"/>
				</fieldset>
				<fieldset class="buttons">
					<g:submitButton name="create" class="save" value="${message(code: 'default.button.create.label', default: 'Create')}" />
				</fieldset>
			</g:form>
		</div>
	</body>
</html>

grails-app/views/book/index.gsp
<%@ page import="webservicetest_two_three_eleven.Book" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'book.label', default: 'Book')}" />
		<title><g:message code="default.list.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#list-book" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="list-book" class="content scaffold-list" role="main">
			<h1><g:message code="default.list.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
				<div class="message" role="status">${flash.message}</div>
			</g:if>
			<table>
			<thead>
					<tr>
					
						<g:sortableColumn property="author" title="${message(code: 'book.author.label', default: 'Author')}" />
					
						<g:sortableColumn property="title" title="${message(code: 'book.title.label', default: 'Title')}" />
					
					</tr>
				</thead>
				<tbody>
				<g:each in="${bookInstanceList}" status="i" var="bookInstance">
					<tr class="${(i % 2) == 0 ? 'even' : 'odd'}">
					
						<td><g:link action="show" id="${bookInstance.id}">${fieldValue(bean: bookInstance, field: "author")}</g:link></td>
					
						<td>${fieldValue(bean: bookInstance, field: "title")}</td>
					
					</tr>
				</g:each>
				</tbody>
			</table>
			<div class="pagination">
				<g:paginate total="${bookInstanceCount ?: 0}" />
			</div>
		</div>
	</body>
</html>